### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by directoryio** [saracen/directory.io#10]
Deleted spam.

**Comment by Zeeko22** [comment]
I sell also bitcoin addresses!!!! 100.000 for 1BTC. !!!! Lol

**Comment by i-socteur** [comment]
Hello, Arran, greate thanks for this project! im your FAN))) - i start to learn Go-lang some time ago only to have an ability to start with directory)))))), im Alex (sometimes it even seems to me that this you influence the bitcoin rate with your updates- ha-ha!!!!)  all your projects are brilliant.... i also try to attach some js. to code to observe activity,but  i want to use this your solution (true/false -! its So Good!!!!!!)) - How much is it? or here my mail - mess@bk.ru  - if you can))))))))))))))))))))))) Have a Good day! Nice Job!!

**Comment by Zeeko22** [comment]
Hi.

can u share she code ? looks very intresting..

**Comment by killyou007** [comment]
hi

i would like to buy the code, because i lost my private key.
at least try in this way. let me know the price and other details.
thanks in advance and waiting for the response asap...

Regards,
Killer King

**Comment by directoryio** [comment]
Hi killyou007 the price is 0.01 btc

**Comment by directoryio** [comment]
My personal mail is angerfist2016@gmail.com for details

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by Zeeko22** [comment]
Github admins shall ban this guy!!!!!  Sorry if u felt for his ripp... ofcourse there is no and Address prefix search for directory.... !!! Its like to build a living tree again from your old tree table!!!  You can mkae the table from the tree but u cant make trees of tables!!!! The privatekey is the tree and address is the tables !!!

**Comment by killyou007** [comment]
hi

everybody knows it's not possible.
but i wanted just recover my private key, then i asked him.
he said he has a software and provide me.
so i paid amount in bitcoins. paid 4 times.
he just gave me a password protected file.
when i ask for password he is not responding since 2 days.
he cheated me. now i got his complete personal info.
i would like to file a lawsuit against him.
he thinks it's just joke. he is playing games with me.
i won't leave him. i have friends on google and apple.
who helped me to get his complete personal info.
(including personal details, contact info ip address & location etc..)
i will post on all social media and file a complaint.
just waiting how long he will hide from me.

anyway thanks for your support.

Regards,
Killer King

**Comment by killyou007** [comment]
i bought huge amount in bitcoins in 2011
at that time the worth is not much.
now it's in millions.
but lost the key, so trying to recover.
i used amazon aws (10s of gpu servers) for 1 year and spent a lot of money for that.
i thought he could help me, but he cheated.
i found another solution, but it's totally math's based.
i am unable to solve it.
of course nobody can crack private key from address.
but there is a biggest secret in address, which gives you exact location.
means in which numbers you have your key.
but unable to find exact number, researching since a year.
hired many people to solve that math's issue.
paid a lot of money, but nobody is perfect.
if we can resolve that calculation, then we can find exact key.
tried with 100s of private keys.
getting same method, but unable to find, but where the difference coming from.
that's why i trusted him, i thought he could help me in that.
but cheated me and playing games with me.
whatever happens i won't leave him...

**Comment by Zeeko22** [comment]
Do you mean its a way to find the place of privatekey just from an address?? 

If so i thinks its totaly wrong !  can you sahre some info about that very intrested to see , i mean people would empy teh big addresses easly than if this case was true!! plss dont trust in people to pay money ! feel sorry for u!

**Comment by saracen** [comment]
The user @directoryio has nothing to do with this project. Don't try to buy anything from them. If you've been scammed, move on and stop spamming the issues of this project.
